### ISSUE TITLE
Uncaught ReferenceError: fs is not defined

### ISSUE THREAD

**Issue by briandavidwetzel** [fabianfiorotto/quick-query#14]
[Enter steps to reproduce below:]

1. run a query on postgres connection
2. right click results
3. save as csv
(BTW I have just added a `fs = require('fs')` to quick-query-result-view.coffee and it is working for me.  If this works for you, I can PR.)
Thanks for your great work.  I appreciate the product.
 
**Atom Version**: 1.3.2
**System**: Mac OS X 10.10
**Thrown From**: [quick-query](https://github.com/fabianfiorotto/quick-query) package, v0.6.1

### Stack Trace

Uncaught ReferenceError: fs is not defined

```
At /Users/briandavidwetzel/.atom/packages/quick-query/lib/quick-query-result-view.coffee:139

ReferenceError: fs is not defined
    at /Users/briandavidwetzel/.atom/packages/quick-query/lib/quick-query-result-view.coffee:139:13
    at /Users/briandavidwetzel/.atom/packages/quick-query/node_modules/json2csv/lib/json2csv.js:22:9
    at createColumnContent (/Users/briandavidwetzel/.atom/packages/quick-query/node_modules/json2csv/lib/json2csv.js:132:3)
    at /Users/briandavidwetzel/.atom/packages/quick-query/node_modules/json2csv/lib/json2csv.js:21:7
    at createColumnTitles (/Users/briandavidwetzel/.atom/packages/quick-query/node_modules/json2csv/lib/json2csv.js:96:3)
    at /Users/briandavidwetzel/.atom/packages/quick-query/node_modules/json2csv/lib/json2csv.js:19:5
    at checkParams (/Users/briandavidwetzel/.atom/packages/quick-query/node_modules/json2csv/lib/json2csv.js:75:3)
    at module.exports (/Users/briandavidwetzel/.atom/packages/quick-query/node_modules/json2csv/lib/json2csv.js:17:3)
    at QuickQueryResultView.module.exports.QuickQueryResultView.saveCSV (/Users/briandavidwetzel/.atom/packages/quick-query/lib/quick-query-result-view.coffee:135:9)
    at space-pen-div.QuickQueryResultView.atom.commands.add.quick-query:save-csv (/Users/briandavidwetzel/.atom/packages/quick-query/lib/quick-query-result-view.coffee:14:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1016:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:10.5.0 tree-view:toggle (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-dark-ui)
     -2:04.8.0 quick-query:toggle-browser (atom-pane.pane.active)
     -2:02.8.0 quick-query:run (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-dark-ui)
     -1:59.7.0 quick-query:new-connection (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-dark-ui)
     -1:50.4.0 core:confirm (button#quick-query-connect.btn.btn-default.icon.icon-plug)
     -1:33.9.0 quick-query:set-default (div.header.list-item.qq-database-item)
     -1:28.9.0 command-palette:toggle (atom-pane.pane.active)
  5x -1:26.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:23.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:22.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:22.8.0 quick-query:new-editor (atom-pane.pane.active)
     -1:19.8.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -1:17.4.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:12.8.0 editor:select-to-first-character-of-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:11.1.0 quick-query:run (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-light-syntax.theme-one-dark-ui)
  2x -0:50.7.0 quick-query:save-csv (td.selected)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/briandavidwetzel/code/",
    "themes": [
      "one-dark-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.10.3
autocomplete-ruby, v0.1.0
floobits, v0.29.3
language-ember-htmlbars, v0.3.0
minimap, v4.16.2
quick-query, v0.6.1
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by fabianfiorotto** [comment]
Done. I hope this works.
