### ISSUE TITLE
Uncaught TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by agusdiyansyah** [fabianfiorotto/quick-query#16]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Microsoft Windows 10 Pro
**Thrown From**: [quick-query](https://github.com/fabianfiorotto/quick-query) package, v0.7.0

### Stack Trace

Uncaught TypeError: Cannot read property 'constructor' of undefined

```
At C:\Users\agusdiyansyah\.atom\packages\quick-query\node_modules\mysql\lib\protocol\Parser.js:77

TypeError: Cannot read property 'constructor' of undefined
    at Query._callback (C:/Users/agusdiyansyah/.atom/packages/data-atom/lib/data-managers/mysql-manager.js:48:53)
    at Query.Sequence.end (C:\Users\agusdiyansyah\.atom\packages\quick-query\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
    at Query._handleFinalResultPacket (C:\Users\agusdiyansyah\.atom\packages\quick-query\node_modules\mysql\lib\protocol\sequences\Query.js:144:8)
    at Query.EofPacket (C:\Users\agusdiyansyah\.atom\packages\quick-query\node_modules\mysql\lib\protocol\sequences\Query.js:128:8)
    at Protocol._parsePacket (C:\Users\agusdiyansyah\.atom\packages\quick-query\node_modules\mysql\lib\protocol\Protocol.js:280:23)
    at Parser.write (C:\Users\agusdiyansyah\.atom\packages\quick-query\node_modules\mysql\lib\protocol\Parser.js:73:12)
    at Protocol.write (C:\Users\agusdiyansyah\.atom\packages\quick-query\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (C:\Users\agusdiyansyah\.atom\packages\quick-query\node_modules\mysql\lib\Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

### Commands

```
     -5:12 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -3:57.7.0 quick-query:new-editor (div.package-detail.panels-item)
     -3:49.3.0 quick-query:find-table-to-select (div.package-detail.panels-item)
  7x -3:34.7.0 data-atom:execute (atom-text-editor.editor.is-focused)
  2x -2:32.3.0 data-atom:toggle-query-source (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:28.6.0 data-atom:new-connection (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -2:18 data-atom:toggle-results-view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
  3x -2:17.1.0 data-atom:execute (atom-text-editor.editor.is-focused)
     -1:30.2.0 quick-query:run (atom-text-editor.editor.is-focused)
 14x -1:04.9.0 core:undo (atom-text-editor.editor.is-focused)
     -0:56.3.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:56.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:47.8.0 data-atom:execute (atom-text-editor.editor.is-focused)
     -0:45.4.0 core:select-all (atom-text-editor.editor.mini.is-focused)
 11x -0:43.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:30 core:select-all (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "quick-query"
    ],
    "packagesWithKeymapsDisabled": []
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-paths, v1.0.2
bootstrap3-snippets, v0.1.2
color-picker, v2.1.1
data-atom, v0.18.1
emmet, v2.4.1
jQuery, v1.2.1
jquery-snippets, v11.0.0
language-nginx, v0.6.1
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by fabianfiorotto** [comment]
I think this error occurs due a incompatibility with data-atom. I updated node-mysql hoping that it can fix the problem.
