### ISSUE TITLE
Uncaught Error: Connection lost: The server closed the connection.

### ISSUE THREAD

**Issue by md2perpe** [fabianfiorotto/quick-query#3]
Steps to reproduce:

1. Shut down the db server

Some better handling of the error is recommended.

**Atom Version**: 0.201.0
**System**: Windows 7 Professional
**Thrown From**: [quick-query](https://github.com/fabianfiorotto/quick-query) package, v0.2.0

### Stack Trace

Uncaught Error: Connection lost: The server closed the connection.

```
At events.js:141

Error: Connection lost: The server closed the connection.
  at Protocol.end (C:\Users\Per\.atom\packages\quick-query\node_modules\mysql\lib\protocol\Protocol.js:103:13)
  at Socket.<anonymous> (C:\Users\Per\.atom\packages\quick-query\node_modules\mysql\lib\Connection.js:98:28)
  at emitNone (events.js:72:20)
  at Socket.emit (events.js:163:7)
  at _stream_readable.js:891:16
  at process._tickCallback (node.js:357:13)

```

### Commands

```
  2x -6:43.9.0 core:move-down (atom-pane.pane.active)
  2x -6:43.1.0 core:move-left (atom-pane.pane.active)
     -5:59.8.0 quick-query:run (atom-text-editor.editor.is-focused)
     -5:51.7.0 pane:show-next-item (ul.list-inline.tab-bar.inset-panel)
     -5:49.9.0 pane:show-previous-item (ul.list-inline.tab-bar.inset-panel)
  2x -5:49.3.0 pane:show-next-item (atom-text-editor.editor.is-focused)
  2x -5:47.8.0 pane:show-previous-item (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
  2x -5:46.5.0 pane:show-next-item (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -5:43.3.0 pane:show-previous-item (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -3:21 pane:show-next-item (ul.list-inline.tab-bar.inset-panel)
     -3:07.9.0 core:close (ul.list-inline.tab-bar.inset-panel)
     -3:06.6.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -2:36.2.0 core:close (div.settings-view.pane-item)
     -1:54.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:37.6.0 editor:select-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -1:37.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "composer"
    ]
  },
  "quick-query": {
    "resultsInTab": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.6
minimap, v4.9.0
quick-query, v0.2.0

# Dev
No dev packages
```

**Comment by fabianfiorotto** [comment]
I'm handling this exception now.
