### ISSUE TITLE
Uncaught ReferenceError: editor is not defined

### ISSUE THREAD

**Issue by md2perpe** [fabianfiorotto/quick-query#4]
1. Run `SHOW DATABASES`
2. Run `USE test` (or other database)

**Atom Version**: 0.201.0
**System**: Unknown Windows Version
**Thrown From**: [quick-query](https://github.com/fabianfiorotto/quick-query) package, v0.2.0

### Stack Trace

Uncaught ReferenceError: editor is not defined

```
At C:\Users\Per\.atom\packages\quick-query\node_modules\mysql\lib\protocol\Parser.js:82

ReferenceError: editor is not defined
  at C:\Users\Per\.atom\packages\quick-query\lib\quick-query.coffee:120:27
  at Query._callback (C:\Users\Per\.atom\packages\quick-query\lib\quick-query-mysql-connection.coffee:90:7)
  at Query.Sequence.end (C:\Users\Per\.atom\packages\quick-query\node_modules\mysql\lib\protocol\sequences\Sequence.js:96:24)
  at Query._handleFinalResultPacket (C:\Users\Per\.atom\packages\quick-query\node_modules\mysql\lib\protocol\sequences\Query.js:144:8)
  at Query.OkPacket (C:\Users\Per\.atom\packages\quick-query\node_modules\mysql\lib\protocol\sequences\Query.js:78:10)
  at Protocol._parsePacket (C:\Users\Per\.atom\packages\quick-query\node_modules\mysql\lib\protocol\Protocol.js:271:23)
  at Parser.write (C:\Users\Per\.atom\packages\quick-query\node_modules\mysql\lib\protocol\Parser.js:77:12)
  at Protocol.write (C:\Users\Per\.atom\packages\quick-query\node_modules\mysql\lib\protocol\Protocol.js:39:16)
  at Socket.<anonymous> (C:\Users\Per\.atom\packages\quick-query\node_modules\mysql\lib\Connection.js:92:28)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```

### Commands

```
     -4:14.1.0 timecop:view (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -3:54.8.0 symbols-view:toggle-file-symbols (ul.list-inline.tab-bar.inset-panel)
     -3:48.6.0 symbols-view:toggle-project-symbols (ul.list-inline.tab-bar.inset-panel)
     -3:45.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -3:45.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -2:49.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:49.6.0 quick-query:new-editor (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:43.1.0 quick-query:toggle-browser (atom-text-editor.editor.is-focused)
     -1:40.7.0 quick-query:new-connection (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:17.5.0 quick-query:run (atom-text-editor.editor.is-focused)
     -1:11.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:06.7.0 quick-query:run (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "tab-switcher"
    ]
  }
}
```

### Installed Packages

```coffee
# User
keyboard-localization, v1.4.0
localization, v1.16.1
quick-query, v0.2.0

# Dev
No dev packages
```

**Comment by fabianfiorotto** [comment]
I published an update for this.
