### ISSUE TITLE
Uncaught TypeError: Cannot read property 'showOpenDialog' of undefined

### ISSUE THREAD

**Issue by sinkcup** [fabianfiorotto/quick-query#40]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [quick-query](https://github.com/fabianfiorotto/quick-query) package 0.10.1

### Stack Trace

Uncaught TypeError: Cannot read property 'showOpenDialog' of undefined

```
At /home/ubuntu/.atom/packages/quick-query/lib/quick-query-connect-view.coffee:57

TypeError: Cannot read property 'showOpenDialog' of undefined
    at /packages/quick-query/lib/quick-query-connect-view.coffee:57:22)
    at HTMLButtonElement.dispatch (/packages/quick-query/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/quick-query/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -0:32.5.0 quick-query:toggle-browser (input.hidden-input)
     -0:30.9.0 quick-query:new-connection (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:21 core:cancel (button#quick-query-browse-file.btn.btn-default.icon.icon-file-directory)
     -0:15.4.0 quick-query:new-connection (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:07.4.0 core:cancel (atom-pane.pane)
     -0:05.5.0 quick-query:new-connection (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:00.2.0 core:cancel (button#quick-query-browse-file.btn.btn-default.icon.icon-file-directory)
```

### Non-Core Packages

```
atom-autocomplete-php undefined 
atom-ctags 5.1.0 
autocomplete-php 0.3.7 
busy-signal 1.4.3 
ex-mode 0.15.0 
hyperclick 0.1.1 
improved-autocomplete-php 1.1.1 
intentions 1.1.2 
linter 2.2.0 
linter-eslint 8.2.1 
linter-php 1.3.2 
linter-phpcs 1.6.7 
linter-ui-default 1.6.2 
php-integrator-autocomplete-plus 1.5.0 
php-integrator-call-tips 1.2.1 
php-integrator-navigation 1.1.2 
php-integrator-tooltips 1.1.5 
quick-query 0.10.1 
quick-query-sqlite 0.3.1 
vim-mode-plus 0.93.0 
```

**Comment by fabianfiorotto** [comment]
I already fixed this in #36 but it seems like they decided to change it ...again. Probably this change will break compatibility with atom 1.17 but I 'm realizing that offer backward compatibility in atom is impossible. 

Also, remember that you can open sqlite databases directly from the tree view.
