### ISSUE TITLE
Uncaught TypeError: resultView.stopLoop is not a function

### ISSUE THREAD

**Issue by deem0n** [fabianfiorotto/quick-query#48]
[Enter steps to reproduce:]

1. If your postgres session is expired (timed out) and you try to run SQL with F5, you see a small popup titled Running query. If you press `Escape` - you see this error

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [quick-query](https://github.com/fabianfiorotto/quick-query) package 0.12.1

### Stack Trace

Uncaught TypeError: resultView.stopLoop is not a function

```
At /Users/deem0n/.atom/packages/quick-query/lib/quick-query.coffee:408

TypeError: resultView.stopLoop is not a function
    at Object.cancel (/packages/quick-query/lib/quick-query.coffee:408:20)
    at /packages/quick-query/lib/quick-query.coffee:121:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -1:42.1.0 editor:indent (input.hidden-input)
     -1:40.5.0 core:backspace (input.hidden-input)
     -1:37 core:copy (input.hidden-input)
     -1:35.9.0 core:paste (input.hidden-input)
  4x -1:34.5.0 core:backspace (input.hidden-input)
     -1:12.9.0 core:copy (input.hidden-input)
     -1:10.3.0 core:paste (input.hidden-input)
  4x -1:06.8.0 core:backspace (input.hidden-input)
     -1:02.9.0 core:move-right (input.hidden-input)
     -1:00.4.0 inline:clear-current (input.hidden-input)
     -1:00.4.0 autocomplete-plus:cancel (input.hidden-input)
     -0:55 core:save (input.hidden-input)
     -0:47.8.0 quick-query:run (input.hidden-input)
     -0:41 quick-query:set-default (div.header.list-item.qq-database-item)
     -0:39 quick-query:run (ol#quick-query-connections.list-tree.has-collapsable-children.focusable-panel)
  2x -0:15 core:cancel (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
```

### Non-Core Packages

```
api-workbench 0.8.47 
atom-beautify 0.30.5 
atom-commander 0.10.2 
busy-signal 1.4.3 
dash 1.7.1 
elm-format 3.0.0 
elmjutsu 6.0.0 
git-plus 7.9.3 
ink 0.7.6 
intentions 1.1.5 
julia-client 0.6.3 
language-elm 1.5.0 
language-elmx 2.1.1 
language-haskell 1.14.1 
language-julia 0.12.0 
language-lua 0.9.11 
language-pgsql 0.2.3 
language-scheme 1.4.0 
latex-completions 0.3.3 
linter 2.2.0 
linter-ui-default 1.6.10 
proto-repl 1.4.21 
proto-repl-charts 0.4.1 
quantum-shell 0.7.1 
quick-query 0.12.1 
regex-railroad-diagram 0.19.4 
Sublime-Style-Column-Selection 1.7.4 
tool-bar 1.1.0 
uber-juno 0.1.2 
```

**Comment by fabianfiorotto** [comment]
I couldn't reproduce the error but I'm sure that this update is going to fix it.
