### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by rrouterr** [fabianfiorotto/quick-query#66]
**Atom version: 1.54.0

on install i have error message

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Users\\Michał\\AppData\\Local\\atom\\app-1.54.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\Michał\\AppData\\Local\\atom\\app-1.54.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\Michał\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\Michał\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/quick-query/versions/1.1.1/tarball',
1 verbose cli   '--target=6.1.12',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.4.0
4 verbose npm-session 14a6df660cabb505
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/fabianfiorotto/quick-query/legacy.tar.gz/v1.1.1 1084ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/quick-query/versions/1.1.1/tarball fetched in 1107ms
9 timing stage:loadCurrentTree Completed in 1118ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 0ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule quick-query@1.1.1 checking installable status
17 silly fetchPackageMetaData error for mysql@git+https://github.com/fabianfiorotto/mysql.git#qq001 Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/fabianfiorotto/mysql.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 http fetch GET 304 https://registry.npmjs.org/atom-space-pen-views 121ms (from cache)
19 silly pacote range manifest for atom-space-pen-views@^2.0.3 fetched in 124ms
20 silly resolveWithNewModule atom-space-pen-views@2.2.0 checking installable status
21 http fetch GET 304 https://registry.npmjs.org/json2csv 107ms (from cache)
22 silly pacote version manifest for json2csv@3.2.0 fetched in 110ms
23 silly resolveWithNewModule json2csv@3.2.0 checking installable status
24 http fetch GET 304 https://registry.npmjs.org/ssh2 131ms (from cache)
25 http fetch GET 304 https://registry.npmjs.org/pg 112ms (from cache)
26 silly pacote version manifest for ssh2@0.6.1 fetched in 137ms
27 silly resolveWithNewModule ssh2@0.6.1 checking installable status
28 silly pacote range manifest for pg@^7.6.1 fetched in 116ms
29 silly resolveWithNewModule pg@7.18.2 checking installable status
30 timing stage:rollbackFailedOptional Completed in 0ms
31 timing stage:runTopLevelLifecycles Completed in 1266ms
32 silly saveTree apm-install-dir-202118-132-1aj87d2.swp4
32 silly saveTree `-- quick-query@1.1.1
32 silly saveTree   +-- atom-space-pen-views@2.2.0
32 silly saveTree   +-- json2csv@3.2.0
32 silly saveTree   +-- pg@7.18.2
32 silly saveTree   `-- ssh2@0.6.1
33 verbose stack Error: spawn git ENOENT
33 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
33 verbose stack     at onErrorNT (internal/child_process.js:456:16)
33 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:9)
34 verbose cwd C:\Users\MICHA~1\AppData\Local\Temp\apm-install-dir-202118-132-1aj87d2.swp4
35 verbose Windows_NT 10.0.19042
36 verbose argv "C:\\Users\\Michał\\AppData\\Local\\atom\\app-1.54.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Michał\\AppData\\Local\\atom\\app-1.54.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Michał\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Michał\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/quick-query/versions/1.1.1/tarball" "--target=6.1.12" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
37 verbose node v12.4.0
38 verbose npm  v6.14.8
39 error code ENOENT
40 error syscall spawn git
41 error path git
42 error errno ENOENT
43 error enoent Error while executing:
43 error enoent undefined ls-remote -h -t https://github.com/fabianfiorotto/mysql.git
43 error enoent
43 error enoent
43 error enoent spawn git ENOENT
44 error enoent This is related to npm not being able to find a file.
45 verbose exit [ 1, true ]

**Comment by rjousse18** [comment]
add git-core to the path environment

https://stackoverflow.com/questions/49256190/how-to-fix-git-sh-setup-file-not-found-in-windows#comment88245403_49256190
